[package]

name = "rust-projectEuler"
version = "0.0.1"
authors = ["Adrian Obelmejias obeladrian@gmail.com"]

# [[lib]]
#
# name = "problems"
# # path = "problems/lib.rs"
# #
[[bin]]

name = "projecteuler"
